### ISSUE TITLE
Provide patterns for the format column

### ISSUE THREAD

**Issue by markiewb** [imgruntw/date-time-converter-plugin#2]
Is it possible to add an editable dropdown when a cell of the "Format" column is edited?

With some standard patterns like
* dd/MM/yyyy - HH:mm:ss.SSS
* dd/MM/yyyy - HH:mm:ss
* yyyy-MM-dd'T'HH:mm:ss.SSSZ
* yyyy-MM-dd'T'HH:mm:ss.SSSXXX
* shortDateTime, mediumDateTime, longDateTime - http://www.joda.org/joda-time/apidocs/org/joda/time/format/DateTimeFormat.html

**Comment by imgruntw** [comment]
yes, it is possible

**Comment by imgruntw** [comment]
editable dropdown is now available with following default patterns:
- dd/MM/yyyy - HH:mm:ss.SSS
- dd/MM/yyyy - HH:mm:ss
- dd/MM/yyyy - HH:mm
- dd/MM/yyyy - HH
- dd/MM/yyyy'T'HH:mm:ss.SSSZ

@markiewb Various other patterns could be make user specific in plugin preferences. So, what do you think?

**Comment by markiewb** [comment]
@imgruntw Thanks for your effort! 

I had to think over my original request. Setting the cell formatter for each cell is very tedious. Instead a simple option in the preferences to select the pattern may be sufficient.
