### ISSUE TITLE
Seconds Conversion

### ISSUE THREAD

**Issue by trevrobwhite** [imgruntw/date-time-converter-plugin#5]
This is a great tool, but most of the timestamps I handle are in the seconds (Unixtime) format, can there be an option to swap between ms and sec formats, or maybe the system auto detects based on the number size (although that could be open for error).

Many thanks.

**Comment by imgruntw** [comment]
@trevrobwhite Thanks for the feedback! I consider the possible solution: either a switch button (ms and sec) or additional column.

**Comment by imgruntw** [comment]
@trevrobwhite It is now possible to switch per button between ms and seconds format in timestamp column:
![image](https://user-images.githubusercontent.com/2216633/61687541-f4427480-ad22-11e9-8b7f-069b42a5119a.png)

**Comment by trevrobwhite** [comment]
@imgruntw That's perfect thanks
